version: '3.8'
services:
  odoo:
    container_name: odoo
    build: ./docker/odoo
    depends_on:
      - db
    ports:
      - "8070:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./odoo/addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=password

  db:
    container_name: db
    build: docker/postgres
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=odoo_db
    ports:
      - "15432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data: